[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name="mysite"
requires-python=">=3.12"
version="0.6.9"

dependencies = [
    "fastapi",
    "motor",
]

[tool.setuptools.packages.find]
where = ["."]